version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:80"
    environment:
      - APP_NAME=Laravel
      - APP_ENV=production
      - APP_KEY=base64:G1DUfACktK330FTqUIq/HawJW7Ot/l0uIsRzWyc4wss=
      - APP_DEBUG=false
      - APP_URL=http://backend.192.168.1.10.sslip.io
      - APP_LOCALE=en
      - APP_FALLBACK_LOCALE=en
      - APP_FAKER_LOCALE=en_US
      - APP_MAINTENANCE_DRIVER=file
      - PHP_CLI_SERVER_WORKERS=4
      - BCRYPT_ROUNDS=12
      - LOG_CHANNEL=stack
      - LOG_STACK=single
      - LOG_DEPRECATIONS_CHANNEL=null
      - LOG_LEVEL=info
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=demo_laravel
      - DB_USERNAME=laravel
      - DB_PASSWORD=password
      - SESSION_DRIVER=redis
      - SESSION_LIFETIME=120
      - SESSION_ENCRYPT=false
      - SESSION_PATH=/
      - SESSION_DOMAIN=null
      - BROADCAST_CONNECTION=log
      - FILESYSTEM_DISK=local
      - QUEUE_CONNECTION=redis
      - CACHE_STORE=redis
      - CACHE_PREFIX=
      - MEMCACHED_HOST=127.0.0.1
      - REDIS_CLIENT=phpredis
      - REDIS_HOST=redis
      - REDIS_PASSWORD=null
      - REDIS_PORT=6379
      - MAIL_MAILER=log
      - MAIL_SCHEME=null
      - MAIL_HOST=127.0.0.1
      - MAIL_PORT=2525
      - MAIL_USERNAME=null
      - MAIL_PASSWORD=null
      - MAIL_FROM_ADDRESS=hello@example.com
      - MAIL_FROM_NAME=Laravel
      - AWS_ACCESS_KEY_ID=
      - AWS_SECRET_ACCESS_KEY=
      - AWS_DEFAULT_REGION=us-east-1
      - AWS_BUCKET=
      - AWS_USE_PATH_STYLE_ENDPOINT=false
      - VITE_APP_NAME=Laravel
    volumes:
      - storage_data:/app/storage/app
      - ./storage/logs:/app/storage/logs
    networks:
      - laravel
    restart: unless-stopped

  # Queue worker service
  queue:
    build:
      context: .
      dockerfile: Dockerfile
    command: php artisan queue:work --verbose --tries=3 --timeout=90
    environment:
      - APP_NAME=Laravel
      - APP_ENV=production
      - APP_KEY=base64:G1DUfACktK330FTqUIq/HawJW7Ot/l0uIsRzWyc4wss=
      - APP_DEBUG=false
      - APP_URL=http://backend.192.168.1.10.sslip.io
      - APP_LOCALE=en
      - APP_FALLBACK_LOCALE=en
      - APP_FAKER_LOCALE=en_US
      - APP_MAINTENANCE_DRIVER=file
      - PHP_CLI_SERVER_WORKERS=4
      - BCRYPT_ROUNDS=12
      - LOG_CHANNEL=stack
      - LOG_STACK=single
      - LOG_DEPRECATIONS_CHANNEL=null
      - LOG_LEVEL=info
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=demo_laravel
      - DB_USERNAME=laravel
      - DB_PASSWORD=password
      - SESSION_DRIVER=redis
      - SESSION_LIFETIME=120
      - SESSION_ENCRYPT=false
      - SESSION_PATH=/
      - SESSION_DOMAIN=null
      - BROADCAST_CONNECTION=log
      - FILESYSTEM_DISK=local
      - QUEUE_CONNECTION=redis
      - CACHE_STORE=redis
      - CACHE_PREFIX=
      - MEMCACHED_HOST=127.0.0.1
      - REDIS_CLIENT=phpredis
      - REDIS_HOST=redis
      - REDIS_PASSWORD=null
      - REDIS_PORT=6379
      - MAIL_MAILER=log
      - MAIL_SCHEME=null
      - MAIL_HOST=127.0.0.1
      - MAIL_PORT=2525
      - MAIL_USERNAME=null
      - MAIL_PASSWORD=null
      - MAIL_FROM_ADDRESS=hello@example.com
      - MAIL_FROM_NAME=Laravel
      - AWS_ACCESS_KEY_ID=
      - AWS_SECRET_ACCESS_KEY=
      - AWS_DEFAULT_REGION=us-east-1
      - AWS_BUCKET=
      - AWS_USE_PATH_STYLE_ENDPOINT=false
      - VITE_APP_NAME=Laravel
    volumes:
      - storage_data:/app/storage/app
      - ./storage/logs:/app/storage/logs
    networks:
      - laravel
    restart: unless-stopped

  # Scheduler service
  scheduler:
    build:
      context: .
      dockerfile: Dockerfile
    command: php artisan schedule:work
    environment:
      - APP_NAME=Laravel
      - APP_ENV=production
      - APP_KEY=base64:G1DUfACktK330FTqUIq/HawJW7Ot/l0uIsRzWyc4wss=
      - APP_DEBUG=false
      - APP_URL=http://backend.192.168.1.10.sslip.io
      - APP_LOCALE=en
      - APP_FALLBACK_LOCALE=en
      - APP_FAKER_LOCALE=en_US
      - APP_MAINTENANCE_DRIVER=file
      - PHP_CLI_SERVER_WORKERS=4
      - BCRYPT_ROUNDS=12
      - LOG_CHANNEL=stack
      - LOG_STACK=single
      - LOG_DEPRECATIONS_CHANNEL=null
      - LOG_LEVEL=info
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=demo_laravel
      - DB_USERNAME=laravel
      - DB_PASSWORD=password
      - SESSION_DRIVER=redis
      - SESSION_LIFETIME=120
      - SESSION_ENCRYPT=false
      - SESSION_PATH=/
      - SESSION_DOMAIN=null
      - BROADCAST_CONNECTION=log
      - FILESYSTEM_DISK=local
      - QUEUE_CONNECTION=redis
      - CACHE_STORE=redis
      - CACHE_PREFIX=
      - MEMCACHED_HOST=127.0.0.1
      - REDIS_CLIENT=phpredis
      - REDIS_HOST=redis
      - REDIS_PASSWORD=null
      - REDIS_PORT=6379
      - MAIL_MAILER=log
      - MAIL_SCHEME=null
      - MAIL_HOST=127.0.0.1
      - MAIL_PORT=2525
      - MAIL_USERNAME=null
      - MAIL_PASSWORD=null
      - MAIL_FROM_ADDRESS=hello@example.com
      - MAIL_FROM_NAME=Laravel
      - AWS_ACCESS_KEY_ID=
      - AWS_SECRET_ACCESS_KEY=
      - AWS_DEFAULT_REGION=us-east-1
      - AWS_BUCKET=
      - AWS_USE_PATH_STYLE_ENDPOINT=false
      - VITE_APP_NAME=Laravel
    volumes:
      - storage_data:/app/storage/app
      - ./storage/logs:/app/storage/logs
    networks:
      - laravel
    restart: unless-stopped

networks:
  laravel:
    driver: bridge

volumes:
  mysql_data:
    driver: local
  redis_data:
    driver: local
  storage_data:
    driver: local